services:
    app:
        image: laravel
        container_name: pastelaria_app
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: pastelaria_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pastelaria
            MYSQL_USER:  user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
